version: "3"
services:
  server:
    image: "mitene/terrafire:${TAG:-latest}"
    command: ["server"]
    environment:
      TERRAFIRE_PROJECT_default: "https://github.com/mitene/terrafire"
      TERRAFIRE_PROJECT_default_PATH: "examples/manifest"
      TERRAFIRE_PROJECT_default_BRANCH: "${BRANCH:-master}"
    ports:
      - "8080:8080"
      - "8081:8081"

  controller:
    image: "mitene/terrafire:${TAG:-latest}"
    command: ["controller"]
    environment:
      TERRAFIRE_SCHEDULER_ADDRESS: "server:8081"
      TERRAFIRE_PROJECT_default: "https://github.com/mitene/terrafire"
      TERRAFIRE_PROJECT_default_PATH: "examples/manifest"
      TERRAFIRE_PROJECT_default_BRANCH: "${BRANCH:-master}"
